env:
  APP_VERSION: 1.4.0  #Change the version name here before pushing to build
name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3' # Use your Flutter version

    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Install dependencies
      run: flutter pub get

    - name: Restore .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - name: Build APK
      run: flutter build apk --release

    - name: Build AAB (Android App Bundle)
      run: flutter build appbundle --release

    - name: Rename artifacts
      run: |
        mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/PrepAI-${{ env.APP_VERSION }}.apk
        mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/PrepAI-${{ env.APP_VERSION }}.aab

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: PrepAI-${{ env.APP_VERSION }}
        path: build/app/outputs/flutter-apk/PrepAI-${{ env.APP_VERSION }}.apk

    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: PrepAI-AAB-${{ env.APP_VERSION }}
        path: build/app/outputs/bundle/release/PrepAI-${{ env.APP_VERSION }}.aab

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: "PrepAI-${{ env.APP_VERSION }}"
        tag_name: "v${{ env.APP_VERSION }}"
        files: |
          build/app/outputs/flutter-apk/PrepAI-${{ env.APP_VERSION }}.apk
          build/app/outputs/bundle/release/PrepAI-${{ env.APP_VERSION }}.aab
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
